# Generated by Django 4.1 on 2022-09-01 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(blank=True, max_length=80, verbose_name='主题')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('message', models.TextField(verbose_name='信息')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-created_time'],
            },
        ),
    ]
